apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-initdb-config
  namespace: default
data:
  init.sql: |
    CREATE DATABASE footballteamdatabase;
    CREATE DATABASE sonarqubedb;
    
    CREATE USER sonar WITH PASSWORD 'sonar';
    GRANT ALL PRIVILEGES ON DATABASE sonarqube TO sonar;
